### ISSUE TITLE
[Feature Request] Investigate methods for standardizing kernel function signatures

### ISSUE THREAD

**Issue by mackncheesiest** [ruhrie/TraceAtlas#10]
In the current implementation of `tik`, the signatures for the autogenerated functions vary wildly depending on the kernel.
I'd like to get some input on methods that would enable normalizing these signatures into something that can be used in a runtime that automatically dispatches to these kernels.

For example, this kernel
```
i = 0; x = 1; y = 2; z = 3;
for (; i < 10000; i++) {
  x += y + z;
}
```
gives an LLVM function with four `i32*` arguments with the signature corresponding to `Kernel_0(int* y, int* z, int* x, int* i)`

While this kernel
```
for (i = 0; i < 10000; i++) {
  printf("test\n");
}
```
gives an LLVM function with a single `i32*` argument corresponding to `i`.

Assuming things are restricting to just kernels with `int`/common datatype arguments, a couple of ideas come to mind:
1. Refactor the function signature to accept a single array pointer with i.e. four elements and, in the `init` block of the kernel, assign the globals `@0`, `@1`, `@2`, `@3` to the offsets in this array for each element
2. Refactor the function signature to use variadic arguments and build a runtime that can somehow dispatch to that (not even 100% sure it would be possible in C/C++ since there's no python-esque unpacking operator)

I think ideally, (1) would be the better solution as it could potentially generalize to things like mixed datatypes by making the input pointer act like a struct pointer, and the kernel's `init` code could unpack that struct into all the distinct variables that are used, but I would appreciate any input on the feasibility of this in general.

**Comment by ruhrie** [comment]
So what you said above is correct. The signatures will vary quite wildly right now based on the implementation. Looking at your solutions, I'm not quite sure what you are trying to accomplish. I'll summarize my thoughts of your solutions real quick.
1. This wouldn't be difficult to do, but I'm not sure how this is really that different. It is just a lexical change. Also, remember that the globals are really only just scoped variables per kernel. They aren't truly global.
2. C and C++ have variadic arguments, but I have no clue how these will work in LLVM. This would definitely need exploration. Even if we did change it to accommodate that, we still need to specify the missing variables, and, at least right now, we don't have default values.

Are you just trying to create a normalized interface? Ultimately you will still need to know the layout of these variables in this signature. I'm a bit confused on this and if you could elaborate more I can investigate further.

**Comment by mackncheesiest** [comment]
So the use case in mind is to essentially

1. Use `tik` to extract kernels from an application
2. Compile the output `tik` LLVM to a shared object
3. Give this shared object to a C++ "runtime" system that, together with some metadata about what order to execute kernels in (dependency relationships, etc), opens the shared object, grabs function pointers for each kernel, and executes them in the desired order, ideally in a way that recreates the application's original behavior

The issue with having varied function signatures is that the code for performing dispatch in this runtime is unable to ask "what are your arguments?" and modify its dispatch accordingly since the types of the function pointers (including argument types) are resolved at compile time.
So essentially, yes, it's trying to create a normalized interface.

With applications that we've refactored into kernel functions by hand, we've been getting around this by essentially just keeping track of how many bytes a given application needs to hold all necessary state, `malloc`ing a buffer to hold it all, and passing that in to each kernel (each with identical signatures) which can then update pieces of it as necessary. There still does need to be some knowledge of variable layout, but allocating more or less memory for more or less variables as necessary is trivial at runtime, but swapping out a dispatch call from `(*func_handle)(ptr1)` to `(*func_handle)(ptr1, ptr2)` isn't really possible.

One approach on our side to deal with this would be to include some additional enumeration metadata about "argument types", and then as we're dispatching to handles from the shared object, we can use a giant switch statement, but that's just a bare minimum change that would get us to being able to meaningfully dispatch to these kernels without segfaulting on execution handoff.

**Comment by mackncheesiest** [comment]
As an update here, turns out it wasn't difficult to change our side from handling a single buffer of memory to essentially a symbol table's worth of variables each with a corresponding heap location and pass the pointers in.

The main challenge in scalability is that we are limited by the maximum number of arguments a kernel can have, but in terms of addressing the common case, I think we can handle it from our side just fine.

**Comment by ruhrie** [comment]
So we've been discussing this for a while and this doesn't seem like something that should be done at the IR level. If this is an issue for you the easiest solution for you would be to create a wrapper library. Basically, you create a new function which takes in a pointer to the struct you're referencing, unpacks it in c, and calls our function. This is then mostly a string manipulation problem and shouldn't be too hard.

**Comment by mackncheesiest** [comment]
I'll go ahead and close this for the time being
