### ISSUE TITLE
Unknown keys when parsing trace with cartographer

### ISSUE THREAD

**Issue by mackncheesiest** [ruhrie/TraceAtlas#16]
I have some commits built on top of a6faec5e318a9f92e757d6a3165c258356b9691b (current master) but nothing that changes the cartographer core functionality.

With some codes, only some of the time, cartographer will die in execution at this `throw 2` [here](https://github.com/ruhrie/TraceAtlas/blob/a6faec5e318a9f92e757d6a3165c258356b9691b/cartographer/EncodeDetect.cpp#L160)

I added a print statement to see what the key is that's causing the error, and it usually seems to be some slightly messed up version of a legitimate key i.e.
![image](https://user-images.githubusercontent.com/8922497/72580123-f8ff7400-38d2-11ea-8abf-cfada6f75d7d.png)

Anyone have ideas how to stop it from happening? I think this bad key is legitimately encoded into the trace as repeated runs of cartographer with the same trace file lead to it dying at the same block, but rerunning the trace repeatedly sometimes seems to fix it.

**Comment by mackncheesiest** [comment]
New example:
`Encountered key: LoadAress`

**Comment by ruhrie** [comment]
So we used to see that pseudo frequently and if you extract the trace in question you will see that the trace does in fact exist as you see it. It can happen to the values of the key to btw.

We never quite figured it out, but it is almost certainly due to either our zlib implementation or the treading we tried to put around it. I'll see if I can do something about it, but we honestly haven't seen this issue in months. I assumed it was fixed.

So you say that retracing the executable always fixes the problem for you? Is there anything unusual about the programs you are feeding it? My first inclination is to remove our threading and see if that helps at all. It isn't working properly anyway so there wouldn't be any harm.

**Comment by mackncheesiest** [comment]
It seems to be the case that I can always retry tracing until it does work but sometimes it takes a few tries. Also anecdotally, it seems to happen more if I'm also modifying other files in the directory of the trace file, but I haven't really experimented with it that extensively.

The program is pretty simple, a single main function with some for loops and calls to libc functions (printf, fscanf, fopen, fclose, malloc) that's about 150 lines long. I'd be curious to know what to do to disable threading if only for future reference.

**Comment by ruhrie** [comment]
So the file in question is `BackendTrace.c`. Basically I'll delete everything related to pthreads/remove the semaphores. That is the most likely culprit here by the sounds of it, but its hard to be sure.

If we don't find a solution, that throw is precautionary. It can be removed, and you will only be missing at most 2 values, which isn't enough to invalidate your results.

Tomorrow morning I'll make a new branch with a potential fix for you after I test it.

**Comment by mackncheesiest** [comment]
Another anecdote fwiw: it's seemingly always around 200,000 - 220,000 blocks into processing.
It's never once been that I start analyzing a trace and it immediately fails

**Comment by ruhrie** [comment]
It could be on the zlib boundary then. Odd that you are getting it while we aren't though. We are analyzing traces in the several hundred million blocks and don't see this. Still good to know though.

What OS/llvm/zlib version are you on? Wondering if the environment could be playing some kind of role.

**Comment by mackncheesiest** [comment]
Ubuntu 18.04, LLVM-9, and seemingly zlib 1.2.11 if `zlib1g` is the right apt package

**Comment by ruhrie** [comment]
Try the version that is current in dev. It has all threading removed and a few other improvements. Tik in this branch is still in heavy development though so don't use tik from there.

Let me know if you still have issues. They are likely related to zlib if you do still see them. 

As to your environment, that matches what we are running on. Quick question about your llvm version. Is it from source or the llvm-apt site?

**Comment by mackncheesiest** [comment]
I added the LLVM-9 apt sources from apt.llvm.org (didn't use the autoinstall script) and fetched the packages from there

**Comment by mackncheesiest** [comment]
It seems to still be happening :(
I cherry-picked that commit from dev onto my branch and ended up with this resulting tree
https://github.com/mackncheesiest/TraceAtlas/tree/f5bc95c1a2d9b9ae0ee8ffa5c8a4c2fc2fd754a2

If you could browse through that and let me know if you see any parts I may not have cherry-picked correctly, let me know. In the meantime, I may try building zlib from source and using that

**Comment by mackncheesiest** [comment]
Also there's one commit on top of it that eliminates a reference to `AtlasUtil` that hasn't been merged into master yet, so don't worry I've fixed that

**Comment by ruhrie** [comment]
So to `value` first, no. It was just multiple cooks in the kitchen.

Your branch looks fine to me superficially. This seems to imply one of two things are going wrong. Either our zlib implementation is flawed or your input program is causing unusual behavior.

I'd like you to do two things to help me debug this. First, send me a copy of a source file which causes this. Second, once you do get a trace that fails to parse please extract it with [znet](https://github.com/ruhrie/DashTraceReader) and check if that is actually in the trace or if it is a flaw in cartographer. I'm pretty sure its an issue in the backend, but we should at least check.

**Comment by mackncheesiest** [comment]
Sent the code, and sorry for the delay, got monodevelop working on Ubuntu only to realize that my traces apparently aren't being compressed at all. Passing my trace through `znet` gives an output with exactly the same size, and both are actually completely human readable traces.

Looking at the backend trace code, the code that parses the environment variable that [sets compression level](https://github.com/mackncheesiest/TraceAtlas/blob/14a8358bbc28de5404de4eca6cbcdd0cc0b4db2e/TraceInfrastructure/Backend/BackendTrace.c#L114-L123) seems to be coming _after_ the `deflateInit` call has already happened.
Moving that block to before `deflateInit` and collecting a trace again, it went from 220000 blocks to 3017 blocks from cartographer/dagExtractor's point of view

**Comment by mackncheesiest** [comment]
With this change, though, I'm not able to get the code to fail anymore :man_shrugging: 

Maybe there's a bug in using zlib with a compression level of 0 (assuming that's what the compiler initializes `TraceCompressionLevel` to) where they didn't fully consider someone passing tons of data through zlib without actually compressing anything.

Or maybe the reduction in size to only ~3000 blocks to process made it so that the error doesn't happen (since it was always around the ~200,000 block point before)

**Comment by ruhrie** [comment]
Yeah, compression level 0 does cause issues in my experience. The leading bytes are always slightly off. Didn't know that is caused errors down the line though. The ~200,000 block point is roughly where wee will force compression of the stream because we are at our memory limit. It would be interesting if you got the error again with a program that actually reaches that level again.

Good catch on the compression level, I'll move that up in the dev branch shortly. Don't know how that slipped through. I thought we were still using compressed traces, but maybe that was lost at some point.

**Comment by mackncheesiest** [comment]
For the time being I'll go ahead and close this issue and reopen it if it comes back in the future/I can reliably reproduce it some other way.
