### ISSUE TITLE
Additional documentation requested

### ISSUE THREAD

**Issue by wohlbier** [ruhrie/TraceAtlas#62]
Could you please document what is meant by kernel types?
```
TypeFour, TypeOne, TypeThree, TypeThreeFive, TypeTwo, TypeTwoFive
```

Could you add documentation about how to generate kernel producer consumer relationships? A tool for graphical representation of the results would be great, but I understand if it's not in scope right now.

Thanks!

**Comment by ruhrie** [comment]
So these kernels are just the kernels at different points of the refinement process. I'll go over them briefly here.

Type One: Base kernels extracted from a greedy algorithm
Type Two: Add low frequency blocks to the type one kernel
Type TwoFive: Do Type Two again with the Type Two as the input to grab the remaining missing blocks.
Type Three: Remove the non-recuring blocks from the beginning and end of a kernel.
Type Four: Remove non-recuring blocks from the body of a kernel, effectively splitting fused kernels
Type ThreeFive: Type three again with the Type Four as input.

We provide this information for debug right now, but it isn't intended to be in the final output. It is mainly an internal representation.

To extract the dag use the DagExtractor tool. The tool is currently in flux, hence the lack of documentation on it. It will generate a json of kernel instances and a dictionary of instance ID to kernel name. It currently does have the ability to export a dot file with -d, but it is in beta. All our prior graphics were hand made with the json output, but we are trying to automate it now. If you want more detail on the DagExtractor output feel free to ask and I will provide a more formal write up.

**Comment by ruhrie** [comment]
A quick clarification on the kernel types, the type ThreeFive is the final output which matches the kernel field.

**Comment by wohlbier** [comment]
Thanks.
